### ISSUE TITLE
USER STORY: Resume

### ISSUE THREAD

**Issue by AlexAntony3** [AlexAntony3/AlexDevPath#10]
As a **user**, I want to be **able to see the work history of the Alex**.

**Acceptance Criteria**
1. Job title in work history
2. Date of when the jobs were held. 
3. Clickable to expand job title for a more in depth description.

**Tasks**

 - [x] Create a resume model
 - [x] Design the flow of resume display
 - [x] Add work history to admin panel with CRUD functionality.
