### ISSUE TITLE
USER STORY: Skills

### ISSUE THREAD

**Issue by AlexAntony3** [AlexAntony3/AlexDevPath#14]
As a **user**, I want to be able to **see Alex's skill set**.

**Acceptance Criteria**
1. Show the different types of coding skills
2. Show the different type of hard skills
3. The expertise in each skill must be visible.

**Tasks**

 - [x] Create a skills model.
 - [x] Add skills model to admin panel
 - [x] Allow staff/admin to have CRUD functionality of the skills
 - [x] Show skill types with different and clear icons.
