### ISSUE TITLE
USER STORY: Simple interface

### ISSUE THREAD

**Issue by AlexAntony3** [AlexAntony3/AlexDevPath#24]
As a **staff** user, I expect the **interface to be simple to use**.

**Acceptance Criteria**
1. A clean simple layout for the CRUD functionality. 
2. The functionality is understandable without explanation.

**Tasks**

 - [x] Button for editing items.
 - [x] Buttons for delete items.
 - [x] Button for creating a new element.
