### ISSUE TITLE
USER STORY: Contact page

### ISSUE THREAD

**Issue by AlexAntony3** [AlexAntony3/AlexDevPath#51]
As a **user**, I can **contact Alex** so that **he is aware I'm wanting to contact him**.

**Acceptance Criteria**
1. A clear form
2. A responsive map

**Tasks**

 - [x] Required fields in form
 - [x] Message is sent to admin 
 - [x] A map directing to Newcastle
 - [x] All fields are required
