### ISSUE TITLE
USER STORY:  Education Functionality

### ISSUE THREAD

**Issue by AlexAntony3** [AlexAntony3/AlexDevPath#52]
As a **staff member**, I can **complete full CRUD functionality** so that **the website can be free of errors and up to date*.

**Acceptance Criteria**
1. Full CRUD funtionality
2. Straight forward interface 

**Tasks**

 - [x] Create Education Function
 - [x] View Education Function
 - [x] Edit Education Function
 - [x] Delete Education Function
