### ISSUE TITLE
USER STORY: Projects

### ISSUE THREAD

**Issue by AlexAntony3** [AlexAntony3/AlexDevPath#55]
As a **user**, I can **see all of the projects Alex has been involved** so that **I understand what languages were used and the level of development can be observed*.

**Acceptance Criteria**
1. A clear carousel for project display
2. Skills associated to that project must be displayed

**Tasks**

 - [x] Large project showcase
 - [x] Skills associated to that project are visible
 - [x] GitHub and Live URLs are displayed
