### ISSUE TITLE
General Item: Existing features

### ISSUE THREAD

**Issue by AlexAntony3** [AlexAntony3/AlexDevPath#7]
Add details and screenshots for the following for large and small screen sizes:

- [ ] header
- [ ] navigation
- [ ] views of all pages
- [ ] footer
- [ ] login and logout
- [ ] form CRUD interface
- [ ] admin panel
- [ ] errors
- [ ] Future implementations
